version: '3.3'

services:
  redis:
    image: redis:7.0.8-alpine
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  bot:
    build:
      context: .
    restart: unless-stopped
    command: bash -c "python3 bot.py"
    depends_on:
      - redis
      - db

  worker:
    build:
      context: .
    restart: unless-stopped
    command: celery --app worker.app worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - worker_data:/tmp

  worker_beat:
    build:
      context: .
    command: celery --app worker.app beat --loglevel=info --schedule /tmp/celerybeat-schedule
    restart: unless-stopped
    depends_on:
      - redis
      - db

volumes:
  worker_data:
  postgres_data:
